name         = "otel"
command      = "./run.sh"
restart      = "on-failure"
max_restarts = 3
autostart    = false

[ports]
GRAFANA_PORT     = 3080
TEMPO_HTTP_PORT  = 3200
OTLP_GRPC_PORT   = 4317
OTLP_HTTP_PORT   = 4318
